spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: nomic-embed-text
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  docker:
    compose:
      enabled: true
      skip:
        in-tests: false
      file: docker-compose.yaml
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
