name: dev workflow

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@5
        with:
          java-version: 21
          distribution: temurin
      - run: mvn clean install -DskipTests
        shell: bash
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository/com/sarpreetsingh
          key: sarpreetsingh

  unit-tests:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@5
        with:
          java-version: 21
          distribution: temurin
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository/com/sarpreetsingh
          key: sarpreetsingh
      - run: mvn test -Punit-tests
        shell: bash

  integration-tests:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@5
        with:
          java-version: 21
          distribution: temurin
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository/com/sarpreetsingh
          key: sarpreetsingh
      - run: mvn test -Pintegration-tests
        shell: bash
        env:
          SPRING_PROFILES_ACTIVE: local

  package:
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@5
        with:
          java-version: 21
          distribution: temurin
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository/com/sarpreetsingh
          key: sarpreetsingh
      - run: mvn package -DskipTests
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: target
          path: target
          overwrite: true
          retention-days: 1

  docker-publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: target
          path: target
      - uses: docker/metadata-actions@v6
        id: metadata
        with:
          images:  ${{ secrets.DOCKER_USERNAME }}/nevis
      - uses: docker/login-action@v4
        with:
          username:  ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v4
      - name: build, tag and push the image
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag $USERNAME/nevis:latest \
            --push .